### ISSUE TITLE
Skipping some names

### ISSUE THREAD

**Issue by GreenComfyTea** [pixelsuchter/Bantool-2#27]
So I run big list of 1329255 names by LinoYeen. After it was done, banned list contained all 1329255 names. I decided to run the file again (I renamed banned list) to see if all of them were actually banned. Turned out it was skipping some names. It's pretty inconsistent but approx. each 300 name was not banned. It's banning them right now, going thru the whole list again at ~70 names/second.

During the first run no errors were displayed in console, browsers were opening nicely, no intervention, chunk size 10000, window count 4.

**Comment by pixelsuchter** [comment]
I am currently working on an update, but i haven't quite figured out that bug yet, i'll let you know when i know more. But i am changing the method it uses to run the commands to hopefully be more stable

**Comment by GreenComfyTea** [comment]
Okay!  Nonetheless, the speed is impressive! Thank you for hard work!

**Comment by pixelsuchter** [comment]
This should be fixed with the newest update, sorry for the inconviniences
