### ISSUE TITLE
Windows closing and not reopening

### ISSUE THREAD

**Issue by Charles2532** [pixelsuchter/Bantool-2#28]
I seem to be having an issue where every so often a error will occur and a window will close, until there are no more windows left running the program

Exception ignored in thread started by: <bound method Bantool.browser of <__main__.Bantool object at 0x00000249F0D1D910>>
Traceback (most recent call last):
  File "main.py", line 282, in browser
    chat_field.click()
  File "selenium\webdriver\remote\webelement.py", line 80, in click
  File "selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <textarea class="ScInputBase-sc-1wz0osy-0 ScTextArea-sc-1ywwys8-0 kYJGMC InjectLayout-sc-588ddc-0 iZLAMf tw-textarea tw-textarea--no-resize focus-visible"> is not clickable at point (494,837) because another element <div class="Layout-sc-nxg1ff-0 eVxqWI font-scale--default"> obscures it

Here are my config settings
    "Ban": true,
    "Block": true,
    "Chunk size": 5000,
    "Firefox_profile": "4sc86k42.bantool",
    "Greeting Emote": "",
    "Number_of_browser_windows": 4,
    "Unban": false,
    "Unblock": true,

**Comment by pixelsuchter** [comment]
This should be fixed with the newest update, sorry for the inconviniences
