### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by l1e3e3t7** [pixelsuchter/Bantool-2#30]
I think this tool doesn't work anymore.
It can't find the chat_field with the css selector.
Or am i doing something wrong?

**Comment by pixelsuchter** [comment]
You are probably not doing it wrong. Twitch changes the CSS selector for the pages elements every now and then and every time i need to update them. Thanks for notifying me i will fix this soon.

**Comment by pixelsuchter** [comment]
Ok, with the latest change they turned the chatbox from a simple textfield into a more complex object and i cant access it anymore using a simple CSS selektor. As my Website and javascript knowledge is basically noneexistant, there is not much i can currently do..

**Comment by l1e3e3t7** [comment]
Ok, thank for you for your time and effort.
